numeric_features:
  - project_prf_year_of_project
  - project_prf_functional_size
  - project_prf_max_team_size
  - process_pmf_docs
  - tech_tf_tools_used
  - people_prf_personnel_changes

categorical_features:
  external_eef_industry_sector:
    options: ["Banking", "Insurance", "Manufacturing", "Government", "Healthcare", "Telecommunications", "Other"]
  external_eef_organisation_type:
    options: ["Commercial", "Government", "Non-Profit", "Academic"]
  project_prf_application_type:
    options: ["Management Information System", "Process Control", "Scientific", "Embedded", "Web Application", "Mobile Application"]

one_hot_features:
  application_group:
    input_key: application_group
    mapping:
      "Business Application": project_prf_application_group_business_application
      "Infrastructure Software": project_prf_application_group_infrastructure_software
      "Mathematically Intensive": project_prf_application_group_mathematically_intensive_application
      "Real-time Application": project_prf_application_group_real_time_application

  development_type:
    input_key: development_type
    mapping:
      "New Development": project_prf_development_type_new_development
      "Re-development": project_prf_development_type_re_development

  development_platform:
    input_key: development_platform
    mapping:
      "Mainframe (MR)": tech_tf_development_platform_mr
      "Multi-platform": tech_tf_development_platform_multi
      "PC": tech_tf_development_platform_pc
      "Proprietary": tech_tf_development_platform_proprietary

  language_type:
    input_key: language_type
    mapping:
      "4GL (Fourth Generation)": tech_tf_language_type_4GL
      "5GL (Fifth Generation)": tech_tf_language_type_5GL

  primary_language:
    input_key: primary_language
    mapping:
      "ABAP": tech_tf_primary_programming_language_abap
      "C*": tech_tf_primary_programming_language*c*
      "C": tech_tf_primary_programming_language_c
      "Java": tech_tf_primary_programming_language_java
      "JavaScript": tech_tf_primary_programming_language_javascript
      "Oracle": tech_tf_primary_programming_language_oracle
      "PL/I": tech_tf_primary_programming_language_pl_i
      "Proprietary Agile Platform": tech_tf_primary_programming_language_proprietary_agile_platform

  relative_size:
    input_key: relative_size
    mapping:
      "L (Large)": project_prf_relative_size_l
      "M1 (Medium 1)": project_prf_relative_size_m1
      "M2 (Medium 2)": project_prf_relative_size_m2
      "S (Small)": project_prf_relative_size_s
      "XS (Extra Small)": project_prf_relative_size_xs
      "XXS (Extra Extra Small)": project_prf_relative_size_xxs

  architecture:
    input_key: architecture
    mapping:
      "Client-Server": tech_tf_architecture_client_server
      "Multi-tier with Web Interface": tech_tf_architecture_multi_tier_with_web_public_interface
      "Stand-alone": tech_tf_architecture_stand_alone

  client_server:
    input_key: client_server
    mapping:
      "No": tech_tf_client_server_no
      "Yes": tech_tf_client_server_yes

  web_development:
    input_key: web_development
    mapping:
      "Yes": tech_tf_web_development_tech_tf_web_development
      "No": tech_tf_web_development_web

  dbms_used:
    input_key: dbms_used
    mapping:
      "Yes": tech_tf_dbms_used_tech_tf_dbms_used
      "No": tech_tf_dbms_used_yes

  cost_currency:
    input_key: cost_currency
    mapping:
      "Canadian Dollar": project_prf_cost_currency_canadadollar
      "European Euro": project_prf_cost_currency_europeaneuro

special_cases:
  team_size_group:
    input_key: team_size_group
    options: ["2", "3-4", "5-8", "9-14", "21-30", "41-50", "61-70", "Missing"]
    output_keys:
      "2": project_prf_team_size_group_2
      "3-4": project_prf_team_size_group_3_4
      "5-8": project_prf_team_size_group_5_8
      "9-14": project_prf_team_size_group_9_14
      "21-30": project_prf_team_size_group_21_30
      "41-50": project_prf_team_size_group_41_50
      "61-70": project_prf_team_size_group_61_70
      "Missing": project_prf_team_size_group_Missing

  development_methodology:
    input_key: development_methodology
    mapping:
      "Agile Development/Iterative": process_pmf_development_methodologies_agile_developmentiterative
      "Agile Development/JAD/Multifunctional Teams": process_pmf_development_methodologies_agile_developmentjoint_application_development_jadmultifunctional_teams
      "Agile Development/PSP/Unified Process": process_pmf_development_methodologies_agile_developmentpersonal_software_process_pspunified_process
      "Agile Development/Scrum": process_pmf_development_methodologies_agile_developmentscrum
      "Agile Development/Unified Process": process_pmf_development_methodologies_agile_developmentunified_process
