# Field Help Configuration
# This file contains help text for all form fields in the UI

field_help:
  # Mandatory Fields Help
  project_prf_year_of_project:
    title: "Year of Project"
    help: "The year when the project was initiated or planned to start. This helps account for technological and methodological changes over time."

  external_eef_industry_sector:
    title: "Industry Sector"
    help: "A derived field that summarizes the Organisation Type of the project into a single value of a defined set."

  external_eef_organisation_type:
    title: "Organisation Type"
    help: "Identifies the type of organisation that submitted the project (e.g., Banking, Manufacturing, Retail)."

  project_prf_team_size_group:
    title: "Team Size Group"
    help: "Individual team size: 1 = 1.55, 2 = 1.55 to <2.5, 3-4 = 2.5 to <4.5, 5-8 = 4.5 to <8.5, etc. See ISBSG definition for more details."

  project_prf_max_team_size:
    title: "Max Team Size"
    help: "The maximum number of team members that will work on this project simultaneously. Include developers, testers, analysts, and other active contributors."

  project_prf_relative_size:
    title: "Relative Size"
    help: "Categories the Functional Size (or Adjusted Function Points) by relative sizes: XXS, XS, S, M1, M2, L, XL, XXL, XXXL. See ISBSG for numeric boundaries."

  project_prf_application_type:
    title: "Application Type"
    help: "Identifies the type of application being addressed by the project (e.g., information system, transaction/production system, process control)."

  project_prf_development_type:
    title: "Development Type"
    help: "Describes whether the development was a new development, enhancement, or re-development."

  tech_tf_architecture:
    title: "Architecture"
    help: "Indicates if the application is Stand alone, Multi-tier, Client server, or Multi-tier with web public interface."

  tech_tf_development_platform:
    title: "Development Platform"
    help: "Defines the primary development platform (as determined by the operating system used): PC, Mid Range, Main Frame, or Multi platform. This affects complexity and development approach."

  tech_tf_language_type:
    title: "Language Type"
    help: "Defines the language type used for the project (e.g., 3GL, 4GL, Application Generator, etc.)."

  tech_tf_primary_programming_language:
    title: "Primary Programming Language"
    help: "Primary programming language(s) used in the project. Select the main language or framework that will be used for development."
  #Optional field help
  project_prf_functional_size:
    title: "Functional Size"
    help: "The estimated functional size of the project measured in function points, use cases, or similar metrics. This represents the scope of functionality to be delivered."

  process_pmf_development_methodologies:
    title: "Development Methodologies"
    help: "Methodologies used during development (e.g., Agile, JAD, Waterfall etc.). These methods may apply to any part of the development lifecycle."

  process_pmf_docs:
    title: "Number of Documents Produced"
    help: "Documents or work products produced during various project activities, including planning, specification, design, build, testing, and implementation."

  tech_tf_client_roles:
    title: "Client Roles"
    help: "The roles performed by the computers that provide interface to the software’s external users."

  tech_tf_server_roles:
    title: "Server Roles"
    help: "The services provided by the host/server computer(s) to the software application or product."

  tech_tf_tools_used:
    title: "Number of Tools Used"
    help: "Any software engineering, database, testing, or other tools used during project development or maintenance."

  tech_tf_web_development:
    title: "Web Development"
    help: "A derived indicator of whether the project data includes any comment that it is a web-development project."

  tech_tf_dbms_used:
    title: "DBMS Used"
    help: "Indicates whether the project used a database management system, either in primary or secondary platforms."

  project_prf_case_tool_used:
    title: "CASE Tool Used"
    help: "Whether the project used any Computer-Aided Software Engineering (CASE) tool, such as Upper CASE tool, Lower CASE tool, or Integrated CASE tool."

  process_pmf_prototyping_used:
    title: "Prototyping Used"
    help: "Whether the project used any prototyping techniques during development."

  people_prf_project_user_involvement:
    title: "Number of Business User Involved"
    help: "Indicator of whether business users were assigned to the project."

# Mandatory field configuration
mandatory_fields:
  - project_prf_year_of_project
    - external_eef_industry_sector
    - external_eef_organisation_type
    - project_prf_team_size_group
    - project_prf_max_team_size
    - project_prf_relative_size
    - project_prf_application_type
    - project_prf_development_type
    - tech_tf_architecture
    - tech_tf_development_platform
    - tech_tf_language_type
    - tech_tf_primary_programming_language

# Optional field configuration
optional_fields:
  - project_prf_functional_size
    - people_prf_personnel_changes
    - process_pmf_development_methodologies
    - tech_tf_server_roles
    - tech_tf_client_roles
    - tech_tf_client_server
    - tech_tf_web_development
    - tech_tf_dbms_used
    - process_pmf_prototyping_used
    - project_prf_case_tool_used
    - tech_tf_tools_used
    - process_pmf_docs
    - people_prf_project_user_involvement

# Tab configuration
tab_configuration:
  "Required Fields":
    description: "Essential project parameters needed for accurate estimation"
    fields:
      - project_prf_year_of_project
      - external_eef_industry_sector
      - external_eef_organisation_type
      - project_prf_team_size_group
      - project_prf_max_team_size
      - project_prf_relative_size
      - project_prf_application_type
      - project_prf_development_type
      - tech_tf_architecture
      - tech_tf_development_platform
      - tech_tf_language_type
      - tech_tf_primary_programming_language

  "Optional Fields":
    description: "Additional parameters that can improve estimation accuracy"
    fields:
      - project_prf_functional_size
      - people_prf_personnel_changes
      - process_pmf_development_methodologies
      - tech_tf_server_roles
      - tech_tf_client_roles
      - tech_tf_client_server
      - tech_tf_web_development
      - tech_tf_dbms_used
      - process_pmf_prototyping_used
      - project_prf_case_tool_used
      - tech_tf_tools_used
      - process_pmf_docs
      - people_prf_project_user_involvement
