# UI Configuration File
# Updated to support the mandatory/optional field structure

app_settings:
  default_config_path: "config/feature_mapping.yaml"
  help_config_path: "config/field_help.yaml"  # New: Path to help configuration
  configs_directory: "configs"

# Field labels for display
field_labels:
  project_prf_year_of_project: "Project Year"
  project_prf_functional_size: "Functional Size"
  project_prf_max_team_size: "Max Team Size"
  project_prf_team_size_group: "Team Size Group"
  project_prf_duration_months: "Duration (Months)"
  project_prf_effort_person_months: "Effort (Person-Months)"
  project_prf_programming_language: "Programming Language"
  project_prf_development_platform: "Development Platform"
  project_prf_database_type: "Database Type"
  project_prf_architecture_type: "Architecture Type"
  project_prf_integration_complexity: "Integration Complexity"
  project_prf_security_requirements: "Security Requirements"
  project_prf_performance_requirements: "Performance Requirements"
  project_prf_ui_complexity: "UI Complexity"
  project_prf_testing_strategy: "Testing Strategy"
  project_prf_deployment_strategy: "Deployment Strategy"

# Numeric field configurations
numeric_field_config:
  project_prf_year_of_project:
    min: 2015
    max: 2030
    default: 2024
    input_type: "number_input"
  
  project_prf_functional_size:
    min: 1
    max: 10000
    default: 100
    input_type: "number_input"
  
  project_prf_max_team_size:
    min: 1
    max: 100
    default: 5
    input_type: "number_input"
  
  project_prf_duration_months:
    min: 1
    max: 60
    default: 6
    input_type: "number_input"
  
  project_prf_effort_person_months:
    min: 1
    max: 500
    default: 30
    input_type: "number_input"

# UI behavior settings
ui_behavior:
  multiselect_threshold: 10
  radio_threshold: 4
  selectbox_threshold: 8

# Display configuration for summary
display_config:
  key_parameters_for_summary:
    - project_prf_year_of_project
    - project_prf_functional_size
    - project_prf_max_team_size
    - project_prf_duration_months
    - project_prf_effort_person_months

# Feature importance display settings
feature_importance_display:
  max_features_shown: 15
  precision_decimals: 3
  chart_size:
    width: 10
    height: 8

# Prediction thresholds for warnings
prediction_thresholds:
  low_prediction_warning: 10
  high_prediction_warning: 5000

# Legacy tab organization (now overridden by field_help.yaml)
# This is kept for backward compatibility
tab_organization:
  "Required Fields":
    - project_prf_year_of_project
    - project_prf_functional_size
    - project_prf_max_team_size
    - project_prf_duration_months
    - project_prf_effort_person_months
  
  "Optional Fields":
    - project_prf_programming_language
    - project_prf_development_platform
    - project_prf_database_type
    - project_prf_architecture_type
    - project_prf_integration_complexity
    - project_prf_security_requirements
    - project_prf_performance_requirements
    - project_prf_ui_complexity
    - project_prf_testing_strategy
    - project_prf_deployment_strategy