# ui_config.yaml
# Configuration for UI labels, organization, and field settings

field_labels:
  project_prf_year_of_project: "Project Year"
  external_eef_industry_sector: "Industry Sector"
  external_eef_organisation_type: "Organisation Type"
  project_prf_application_type: "Application Type"
  project_prf_functional_size: "Functional Size (Function Points)"
  project_prf_max_team_size: "Maximum Team Size"
  process_pmf_docs: "Documentation Level (1-5)"
  tech_tf_tools_used: "Development Tools Sophistication (1-5)"
  people_prf_personnel_changes: "Personnel Changes (1-5)"
  project_prf_application_group: "Primary Application Category"
  project_prf_development_type: "Development Type"
  project_prf_relative_size: "Relative Project Size"
  tech_tf_development_platform: "Development Platform"
  tech_tf_language_type: "Programming Language Type"
  tech_tf_primary_language: "Primary Programming Language"
  tech_tf_architecture: "System Architecture"
  tech_tf_client_server: "Client-Server Architecture"
  tech_tf_web_development: "Web Development"
  tech_tf_dbms_used: "Database Management System Used"
  tech_tf_client_roles: "Client Roles"
  tech_tf_server_roles: "Server Roles"
  process_pmf_development_methodologies: "Development Methodologies"
  project_prf_team_size_group: "Team Size Group"
  project_prfcost_currency: "Cost Currency"

tab_organization:
  Basic:
    - project_prf_year_of_project
    - external_eef_industry_sector
    - external_eef_organisation_type
    - project_prf_application_type
    - project_prf_application_group
    - project_prf_development_type
    - project_prf_functional_size
    - project_prf_relative_size
    - project_prf_max_team_size
  Technical:
    - tech_tf_development_platform
    - tech_tf_language_type
    - tech_tf_primary_language
    - tech_tf_architecture
    - tech_tf_client_server
    - tech_tf_client_roles
    - tech_tf_server_roles
    - tech_tf_web_development
    - tech_tf_dbms_used
    - tech_tf_tools_used
  Advanced:
    - process_pmf_docs
    - people_prf_personnel_changes
    - process_pmf_development_methodologies
    - project_prf_team_size_group
    - project_prfcost_currency

numeric_field_config:
  project_prf_year_of_project:
    min: 2015
    max: 2030
    default: 2024
    input_type: "number_input"
  project_prf_functional_size:
    min: 1
    max: 10000
    default: 100
    input_type: "number_input"
  project_prf_max_team_size:
    min: 1
    max: 100
    default: 5
    input_type: "number_input"
  process_pmf_docs:
    min: 1
    max: 100
    default: 3
    input_type: "slider"
  tech_tf_tools_used:
    min: 1
    max: 100
    default: 3
    input_type: "slider"
  people_prf_personnel_changes:
    min: 1
    max: 100
    default: 2
    input_type: "slider"

ui_behavior:
  multiselect_threshold: 10  # Use multiselect if more than this many options
  radio_threshold: 4         # Use radio if less than or equal to this many options
  selectbox_threshold: 8     # Use selectbox if between radio and multiselect thresholds

display_config:
  key_parameters_for_summary:
    - project_prf_year_of_project
    - project_prf_functional_size
    - project_prf_max_team_size
    - external_eef_industry_sector
    - project_prf_application_type
    - process_pmf_docs
    - tech_tf_tools_used
    - people_prf_personnel_changes

prediction_thresholds:
  low_prediction_warning: 1
  high_prediction_warning: 10000

app_settings:
  default_config_path: "config/feature_mapping.yaml"
  ui_config_path: "config/ui_config.yaml"
  configs_directory: "configs"
  models_directory: "models"

feature_importance_display:
  max_features_shown: 15
  chart_size:
    width: 10
    height: 8
  precision_decimals: 3